version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2024-07-15T19-02-30Z.fips
    # docker启动时自动启动
    restart: no
    # 容器名称
    container_name: minio
    # 环境变量
    environment:
      #设置时区
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
      MINIO_SERVER_URL: http://127.0.0.1:9000
    # 端口映射
    ports:
      - "9000:9000"
      - "9090:9090"
    # 数据卷（相关文件夹需要提前建）
    volumes:
      - /mnt/docker/minio/data:/data
    # 指定配置文件启动
    command: server /data --console-address ":9090" --address ":9000"
