version: '3'
services:
  mysql:
    image: mysql:8.0
    # docker启动时自动启动
    restart: always
    # 容器名称
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    # 以下参数是为了解决中文乱码问题
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    # 端口映射
    ports:
      - "3306:3306"
    # 数据卷（相关文件夹需要提前建）
    volumes:
      - /usr/mysql/log:/var/log/mysql
      - /usr/mysql/data:/var/lib/mysql
      - /usr/mysql/conf:/etc/mysql/conf.d