version: '3'
services:
  redis:
    image: redis:7.0.9
    # docker启动时自动启动
    restart: no
    # 容器名称
    container_name: redis
    environment:
      #设置时区
      - TZ=Asia/Shanghai
    # 端口映射
    ports:
      - "36379:6379"
    # 数据卷（相关文件夹需要提前建）
    volumes:
      - /mnt/docker/redis/redis.conf:/etc/redis/redis.conf
      - /mnt/docker/redis/data:/data
    # 指定配置文件启动
    command: redis-server /etc/redis/redis.conf
